name: Automated black formatter
on: [pull_request]
jobs:
  black_formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black
      - name: Run black
        run: black . --check --line-length 79 --force-exclude=\.git
      - name: If needed, commit black changes to a new pull request
        if: failure()
        run: |
          black . --line-length 79 --force-exclude=\.git
          git config --global user.name ab-vikas
          git config --global user.email 'vsharma@atlasbeacon.com'          
          git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Fixup: Format python code with Black"
          git push
